config/routes.rb
Rails.application.routes.draw do

  #devise関連（顧客用）
  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  #devise関連（管理者用）
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }
  #ゲストユーザーログイン
  devise_scope :user do
    post 'users/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end
  
  #About page
  get "about", to: "homes#about", as: "about"
  
  #顧客側routing
  scope module: :public do
    root to: 'practice_posts#index'

    get "search_tag" => "practice_posts#search_tag"
    get "search", to: "searches#search", as: "search"
    get '/users/:id/confirm' => 'users#confirm', as: :user_confirm
    patch 'users/unsubscribe' => 'users#unsubscribe'
    get "maps", to: "maps#index"

    resources :practice_posts, only: [:new, :create, :show, :edit, :index, :update, :destroy] do
      resource :favorites, only: [:create, :destroy]
      resources :post_comments, only: [:create, :destroy]
    end
    resources :users, only: [:index, :show, :edit, :update]
    resources :notifications, only: [:update]
    resources :contacts, only: [:new, :create, :show]
    resources :scores, only: [:index, :new, :create]
    resources :groups, only: [:new, :index, :show, :create, :edit, :update] do
      resource :permits, only: [:create, :destroy]
      resource :group_users, only: [:create, :destroy]
      get "new/mail" => "groups#new_mail"
      get "send/mail" => "groups#send_mail"
      get "permits" => "groups#permits"
    end
  end

  #管理者側routing
  namespace :admin do
    root to: 'users#index'
    resources :users, only: [:index, :show, :edit, :update]
    resources :groups, only: [:index, :destroy]
    resources :post_comments, only: [:index, :destroy]
    resources :tags, only: [:index, :create, :destroy]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  enum subject: {
    bug_report: 0,
    suggestion: 1,
    question: 2,
    other: 3
  }

  validates :name, presence: true
  validates :email, presence: true
  validates :subject, presence: true
  validates :message, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :practice_post
  has_many :notifications, as: :notifiable, dependent: :destroy
  
  after_create :create_notification

  private

  def create_notification
    Notification.create!(
      user: practice_post.user,
      notifiable: self,
      read: false
    )
  end
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_users, dependent: :destroy
  has_many :permits, dependent: :destroy
  belongs_to :owner, class_name: 'User'
  has_many :users, through: :group_users, source: :user

  validates :name, presence: true
  validates :introduction, presence: true
  has_one_attached :group_image

  def is_owned_by?(user)
    owner.id == user.id
  end

  def includesUser?(user)
    group_users.exists?(user_id: user.id)
  end
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :user
  belongs_to :group

  after_create :notify_approval

  private

  def notify_approval
    Notification.create!(
      user: user,
      notifiable: self,
      read: false
    )
  end
end

app/models/hole_score.rb
class HoleScore < ApplicationRecord
  belongs_to :score

  validates :hole_number, presence: true, numericality: { only_integer: true }, inclusion: { in: 1..18 }, uniqueness: { scope: :score_id }
  validates :strokes, numericality: { only_integer: true }, allow_nil: true
  validates :putts, numericality: { only_integer: true }, allow_nil: true
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :user
  belongs_to :notifiable, polymorphic: true

  scope :unread, -> { where(read: false) }
end

app/models/permit.rb
class Permit < ApplicationRecord
  belongs_to :user
  belongs_to :group

  after_create :create_notification

  private

  def create_notification
    Notification.create!(
      user: group.owner,
      notifiable: self,
      read: false
    )
  end
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  belongs_to :user
  belongs_to :practice_post
  has_many :notifications, as: :notifiable, dependent: :destroy

  after_create :create_notification

  validates :comment, presence: true

  private

  def create_notification
    Notification.create!(
      user: practice_post.user,
      notifiable: self,
      read: false
    )
  end
end

app/models/post_tag.rb
class PostTag < ApplicationRecord
  belongs_to :practice_post
  belongs_to :tag
end

app/models/postcomment.rb
class Postcomment < ApplicationRecord
  belongs_to :user
  belongs_to :practice_post

  validates :comment, presence: true
end

app/models/practice_post.rb
class PracticePost < ApplicationRecord
  belongs_to :user
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :post_tags, dependent: :destroy
  has_many :tags, through: :post_tags
  has_many :notifications, as: :notifiable, dependent: :destroy
  has_one_attached :post_image
  has_rich_text :content

  validates :practice_date, :content, presence: :true
  
  geocoded_by :address #addressカラムの内容を緯度・経度に変換
  after_validation :geocode #バリデーションの実行後にカラムに緯度・経度の値が入力される

  def favorited_by?(user)
    return false unless user
    favorites.exists?(user_id: user.id)
  end

  def save_tags(tags)
    current_tags = self.tags.pluck(:name) unless self.post_tags.nil?
    old_tags = current_tags - tags
    new_tags = tags - current_tags
    old_tags.each do |oid_name|
      self.tags.delete Tag.find_by(name:old_name)
    end
    new_tags.uniq.each do |new_name|
      tag = Tag.find_or_create_by(name:new_name)
      self.tags << tag unless self.tags.include?(tag)
    end
  end


end

app/models/score.rb
class Score < ApplicationRecord
  belongs_to :user
  has_many :hole_scores, dependent: :destroy

  validates :date, presence: true
  accepts_nested_attributes_for :hole_scores #Score 保存時にhole_scores_attributes を一緒に保存できるようにする
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :post_tags, dependent: :destroy
  has_many :practice_posts, through: :post_tags

  validates :name, length:{maximum:50}, presence: :true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :practice_posts, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :group_users, dependent: :destroy
  has_many :permits, dependent: :destroy
  has_many :groups, through: :group_users
  has_many :notifications, dependent: :destroy
  has_many :scores, dependent: :destroy
  
  has_one_attached :profile_image

  validates :name, presence: :true
  validates :email, presence: :true

  GUEST_USER_EMAIL = "guest@example.com"

  def self.guest
    find_or_create_by!(email: GUEST_USER_EMAIL) do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "guestuser"
    end
  end


end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "情報を更新しました"
      redirect_to admin_user_path(@user)
    else
      flash.now[:alert] = "情報の更新に失敗しました"
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :is_active)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/helpers/admin/tags_helper.rb
module Admin::TagsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admin/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <h4 class="my-5"><%= @user.name %>さんの会員情報編集</h4>
        <%= form_with model: @user, url: admin_user_path(@user), method: :patch, local: true do |f| %>
        <table class="table table-borderless">
          <tr>
            <td>ユーザーID</td>
            <td><%= @user.id %></td>
          </tr>
          <tr>
            <td>ユーザー名</td>
            <td><%= f.text_field :name %></td>
          </tr>
          <tr>
            <td>メールアドレス</td>
            <td><%= f.text_field :email %></td>
          </tr>
          <tr>
            <td>ステータス</td>
            <td>
              <%= f.radio_button :is_active, true %>
              <%= f.label :is_active_true, '有効' %>

              <%= f.radio_button :is_active, false %>
              <%= f.label :is_active_false, '無効' %>
            </td>
          </tr>
          <tr>
            <td></td>
            <td>
              <%= f.submit "変更を保存", class: "btn btn-success" %>
            </td>
          </tr>
        </table>
        <% end %>
    </div>
  </div>
</div>

          

app/views/admin/users/index.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <h4 class="my-5">ユーザー一覧</h4>
        <table class="table">
          <thead>
            <tr>
              <th>ユーザーID</th>
              <th>ユーザー名</th>
              <th>メールアドレス</th>
              <th>ステータス</th>
            </tr>
          </thead>
          <tbody>
            <% @users.each do |user| %>
              <tr>
                <td><%= user.id %></td>
                <td>
                  <%= link_to "#{user.name}", admin_user_path(user) %>
                </td>
                <td><%= user.email %></td>
                <td>
                  <% if user.is_active %>
                    <div class="text-success">有効</div>
                  <% else %>
                    <div class="text-secondary">無効</div>
                  <% end %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
    </div>
  </div>
</div> 

app/views/admin/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <h4 class="my-5"><%= @user.name %>さんの会員詳細</h4>
      <div class="d-flex align-items-center">
        <table class="table table-borderless">
          <tr>
            <th>会員ID</td>
            <td><%= @user.id %></td>
          </tr>

          <tr>
            <th>ユーザー名</td>
            <td><%= @user.name %></td>
          </tr>
  
          <tr>
            <th>メールアドレス</th>
            <td><%= @user.email %></td>
          </tr>

          <tr>
            <th>ステータス</th>
            <td>
              <% if @user.is_active %>
                <div class="text-success">有効</div>
              <% else %>
                <div class="text-secondary">無効</div>
              <% end %>            
            </td>
          </tr>

          <tr>
            <td></td>
            <td><%= link_to "編集する", edit_admin_user_path, class:"btn btn-success" %>
          </tr>
        </table>
      </div>
    </div>
  </div>
</div>