config/routes.rb
Rails.application.routes.draw do

  #devise関連（顧客用）
  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  #devise関連（管理者用）
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }
  #ゲストユーザーログイン
  devise_scope :user do
    post 'users/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end
  
  #About page
  get "about", to: "homes#about", as: "about"
  
  #顧客側routing
  scope module: :public do
    root to: 'practice_posts#index'

    get "search_tag" => "practice_posts#search_tag"
    get "search", to: "searches#search", as: "search"
    get '/users/:id/confirm' => 'users#confirm', as: :user_confirm
    patch 'users/unsubscribe' => 'users#unsubscribe'
    get "maps", to: "maps#index"

    resources :practice_posts, only: [:new, :create, :show, :edit, :index, :update, :destroy] do
      resource :favorites, only: [:create, :destroy]
      resources :post_comments, only: [:create, :destroy]
    end
    resources :users, only: [:index, :show, :edit, :update]
    resources :notifications, only: [:update]
    resources :contacts, only: [:new, :create, :show]
    resources :scores, only: [:index, :new, :create]
    resources :groups, only: [:new, :index, :show, :create, :edit, :update] do
      resource :permits, only: [:create, :destroy]
      resource :group_users, only: [:create, :destroy]
      get "new/mail" => "groups#new_mail"
      get "send/mail" => "groups#send_mail"
      get "permits" => "groups#permits"
    end
  end

  #管理者側routing
  namespace :admin do
    root to: 'users#index'
    resources :users, only: [:index, :show, :edit, :update]
    resources :groups, only: [:index, :destroy]
    resources :post_comments, only: [:index, :destroy]
    resources :tags, only: [:index, :create, :destroy]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  enum subject: {
    bug_report: 0,
    suggestion: 1,
    question: 2,
    other: 3
  }

  validates :name, presence: true
  validates :email, presence: true
  validates :subject, presence: true
  validates :message, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :practice_post
  has_many :notifications, as: :notifiable, dependent: :destroy
  
  after_create :create_notification

  private

  def create_notification
    Notification.create!(
      user: practice_post.user,
      notifiable: self,
      read: false
    )
  end
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_users, dependent: :destroy
  has_many :permits, dependent: :destroy
  belongs_to :owner, class_name: 'User'
  has_many :users, through: :group_users, source: :user

  validates :name, presence: true
  validates :introduction, presence: true
  has_one_attached :group_image

  def is_owned_by?(user)
    owner.id == user.id
  end

  def includesUser?(user)
    group_users.exists?(user_id: user.id)
  end
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :user
  belongs_to :group

  after_create :notify_approval

  private

  def notify_approval
    Notification.create!(
      user: user,
      notifiable: self,
      read: false
    )
  end
end

app/models/hole_score.rb
class HoleScore < ApplicationRecord
  belongs_to :score

  validates :hole_number, presence: true, numericality: { only_integer: true }, inclusion: { in: 1..18 }, uniqueness: { scope: :score_id }
  validates :strokes, numericality: { only_integer: true }, allow_nil: true
  validates :putts, numericality: { only_integer: true }, allow_nil: true
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :user
  belongs_to :notifiable, polymorphic: true

  scope :unread, -> { where(read: false) }
end

app/models/permit.rb
class Permit < ApplicationRecord
  belongs_to :user
  belongs_to :group

  after_create :create_notification

  private

  def create_notification
    Notification.create!(
      user: group.owner,
      notifiable: self,
      read: false
    )
  end
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  belongs_to :user
  belongs_to :practice_post
  has_many :notifications, as: :notifiable, dependent: :destroy

  after_create :create_notification

  validates :comment, presence: true

  private

  def create_notification
    Notification.create!(
      user: practice_post.user,
      notifiable: self,
      read: false
    )
  end
end

app/models/post_tag.rb
class PostTag < ApplicationRecord
  belongs_to :practice_post
  belongs_to :tag
end

app/models/postcomment.rb
class Postcomment < ApplicationRecord
  belongs_to :user
  belongs_to :practice_post

  validates :comment, presence: true
end

app/models/practice_post.rb
class PracticePost < ApplicationRecord
  belongs_to :user
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :post_tags, dependent: :destroy
  has_many :tags, through: :post_tags
  has_many :notifications, as: :notifiable, dependent: :destroy
  has_one_attached :post_image
  has_rich_text :content

  validates :practice_date, :content, presence: :true
  
  geocoded_by :address #addressカラムの内容を緯度・経度に変換
  after_validation :geocode #バリデーションの実行後にカラムに緯度・経度の値が入力される

  def favorited_by?(user)
    return false unless user
    favorites.exists?(user_id: user.id)
  end

  def save_tags(tags)
    current_tags = self.tags.pluck(:name) unless self.post_tags.nil?
    old_tags = current_tags - tags
    new_tags = tags - current_tags
    old_tags.each do |oid_name|
      self.tags.delete Tag.find_by(name:old_name)
    end
    new_tags.uniq.each do |new_name|
      tag = Tag.find_or_create_by(name:new_name)
      self.tags << tag unless self.tags.include?(tag)
    end
  end


end

app/models/score.rb
class Score < ApplicationRecord
  belongs_to :user
  has_many :hole_scores, dependent: :destroy

  validates :date, presence: true
  accepts_nested_attributes_for :hole_scores #Score 保存時にhole_scores_attributes を一緒に保存できるようにする
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :post_tags, dependent: :destroy
  has_many :practice_posts, through: :post_tags

  validates :name, length:{maximum:50}, presence: :true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :practice_posts, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :group_users, dependent: :destroy
  has_many :permits, dependent: :destroy
  has_many :groups, through: :group_users
  has_many :notifications, dependent: :destroy
  has_many :scores, dependent: :destroy
  
  has_one_attached :profile_image

  validates :name, presence: :true
  validates :email, presence: :true

  GUEST_USER_EMAIL = "guest@example.com"

  def self.guest
    find_or_create_by!(email: GUEST_USER_EMAIL) do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "guestuser"
    end
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_footer.html.erb
<footer class="border-top py-3" style="border-color:black !important;">
  <div class="container">
    <div class="d-flex justify-content-between align-items-center">
      <div class="footer_logo">
        <%= link_to root_path do %>
          <%= image_tag "mygolfnote_logo.png", style: "width: 80px;" %>
        <% end %>
      </div>

      <div class="footer_contact">
        <%= link_to new_contact_path, class: "text-decoration-none font-weight-bold" do %>
          <i class="fa-solid fa-envelope"></i> 運営へのお問い合せ
        <% end %>
      </div>
    </div>

      <div class="text-center mt-2 footer_info">
        <p class="mb-0 small">(c)copyright MyGolfnote 2025 Allrights reserved.</p>
      </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-light">
    <div class="container">
      <%= link_to root_path, class: "navbar-brand" do %>
        <%= image_tag "mygolfnote_logo.png", alt: "MyGolfNote", class: "img-fluid" %>
      <% end %>
      
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
      aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
  
      <% if admin_signed_in? %>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <%= link_to "ユーザー一覧", admin_users_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "グループ一覧", admin_groups_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "コメント一覧", admin_post_comments_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "タグ一覧", admin_tags_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "サインアウト", destroy_admin_session_path, method: :delete, class: "nav-link" %>
            </li>
          </ul>
        </div>
      <% elsif user_signed_in? %>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <%= link_to new_practice_post_path, class: "nav-link", data: {turbolinks: "false"} do %>
                <i class="fa-solid fa-golf-ball-tee"></i> Golf note
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to about_path, class: "nav-link" do %>
                <i class="fa-solid fa-globe"></i> About
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to user_path(current_user), class: "nav-link" do %>
                <i class="fa-solid fa-user-tie"></i> MyPage
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to new_group_path, class: "nav-link" do %>
                <i class="fa-solid fa-users"></i> Group
              <% end %>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle position-relative" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fa-solid fa-bell"></i>
                <% unread_count = current_user.notifications.unread.count %>
                <% if unread_count.positive? %>
                  <span class="badge badge-danger position-absolute" style="top:0; right:0;">
                    <%= unread_count %>
                  </span>
                <% end %>
              </a>

              <div class="dropdown-menu dropdown-menu-right p-2" aria-labelledby="navbarDropdown" style="min-width: 300px;">
                <% if current_user.notifications.where(read: false).any? %>
                  <small class="dropdown-item disabled">直近5件の未読の通知を表示しています</small>
                  <% current_user.notifications.where(read: false).limit(5).order(created_at: :desc).each do |notification| %>
                    <div class="dropdown-item <%= 'font-weight-bold' unless notification.read %>">
                      <%= link_to notification_message(notification), notification_path(notification), method: :patch, class: "text-dark" %>
                      <br>
                      <small class="text-muted"><%= time_ago_in_words(notification.created_at) %>前</small>
                    </div>
                  <% end %>
                <% else %>
                  <span class="dropdown-item text-muted">通知はありません</span>
                <% end %>
              </div>
            </li>
            <li class="nav-item">
              <%= link_to destroy_user_session_path, method: :delete, class: "nav-link" do %>
                <i class="fa-solid fa-right-from-bracket"></i> ログアウト
              <% end %>
            </li>
          </ul>
        </div>
      <% else %>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <%= link_to new_user_registration_path, class: "nav-link" do %>
                <i class="fa-solid fa-address-card"></i> 新規登録
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to new_user_session_path, class: "nav-link" do %>
                <i class="fa-solid fa-right-to-bracket"></i> ログイン
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to about_path, class: "nav-link" do %>
                <i class="fa-solid fa-globe"></i> About
              <% end %>
            </li>
          </ul>
        </div>
      <% end %>
    
    </div>
  </nav>

</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mygolfnote</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/c7023171fe.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column min-vh-100">
    <%= render "layouts/header" %>
    
    <% if controller_name == "practice_posts" && action_name == "index" %>
      <div class="main-visual">
        <div class="main-visual-content">
          <h3 class="main-visual-title display-4 font-weight-bold">MyGolfnote</h3>
          <p class="main-visual-text">あなたのゴルフ練習を記録・共有しよう</p>
          <% if user_signed_in? %>
            <div class="mt-3">
              <%= link_to new_practice_post_path, class: "btn btn-success", data: {turbolinks: "false"} do %>
                <i class="fa-solid fa-golf-ball-tee"></i> Golf note
              <% end %>
            </div>
          <% else %>
            <div class="mt-3">
              <%= link_to new_user_registration_path, class: "btn btn-success sign-up" do %>
                <i class="fa-solid fa-address-card"></i> 新規登録
              <% end %>
              <%= link_to new_user_session_path, class: "btn btn-info ml-1 sign-in" do %>
                <i class="fa-solid fa-right-to-bracket"></i> ログイン
              <% end %>
            </div>
            <div class="mt-2">
              <%= link_to users_guest_sign_in_path, method: :post, class: "btn btn-secondary ml-1 sign-in" do %>
                <i class="fa-solid fa-ghost"></i> ゲストログイン(観覧用)
              <% end %>
            </div>
          <% end %>
        </div>
      </div>
    
    <% elsif controller_name == "groups" && ["index", "new"].include?(action_name) && !controller_path.start_with?("admin/") %>
      <div class="main-visual group-visual">
        <div class="main-visual-content">
          <h3 class="main-visual-title display-4 font-weight-bold">Golf仲間とつながろう</h3>
          <p class="main-visual-text">グループを作成・参加する</p>
          <div class="my-3">
            <%= link_to "Group作成", new_group_path, class: "btn btn-success" %>
            <%= link_to "Group一覧", groups_path, class: "btn btn-info mr-2" %>
          </div>
        </div>
      </div>
    <% end %>
       

    <main>
      <% if flash[:notice] %>
        <div class="flash notice my-3"><%= flash[:notice] %></div>
      <% end %>   
      <% if flash[:alert] %>
        <div class="flash alert my-3"><%= flash[:alert] %></div>
      <% end %>
    
      <% if controller_name == "practice_posts" && action_name == "index" %>
        <div class="container d-flex flex-column align-items-center my-3">
          <h4 class="mb-3">気になるメモを検索</h4>
          <%= render "public/searches/searchform" %>
        </div>
      <% end %>
        
      <%= yield %>
    </main>

    <%= render "layouts/footer" %>
    <script src="https://cdn.jsdelivr.net/npm/jquery-jpostal-ja@2.14.45/jquery.jpostal.min.js"></script> #jquery.jpostal.jsを使用して、郵便番号から住所を自動入力
  </body>
</html>